### PR TITLE
upgrade to minio-go v7

### PR DESCRIPTION
**Pull request by mostynb**
{Put,Get,Stat}Object now take a context, which will come in handy when we implement timeouts for proxy backends (#291).

### CODE REVIEW

**Comment by mostynb** [comment]
@lavignes: I wonder if you could test this branch, to confirm that it still works with IAM?

**Comment by lavignes** [comment]
I can give it a try!

**Comment by lavignes** [comment]
@mostynb Seems to be working just fine :)

**Comment by mostynb** [comment]
Thanks!

**Pull request merged**
