### PR TITLE
don't require explicit empty blob uploads for HTTP either

### PR DESCRIPTION
**Pull request by mostynb**
The gRPC API implementation has a hack to handle clients (like bazel?) which in some cases don't upload the empty blob, but do reference it. It is kind of OK not to upload the empty blob, since it can be recognised by hash and trivially regenerated.

Let's imlpement the hack for the HTTP API also.

Implements #233.

### CODE REVIEW

**Comment by mostynb** [comment]
@brentleyjones: would you like to cherry-pick + test this with your setup?

**Comment by brentleyjones** [comment]
@mostynb Yes! I'll report back soon-ish. Thanks!

**Comment by brentleyjones** [comment]
@mostynb This patch worked. BuildBarn is now able to validate AC's for HTTP mode with this patch.

Sadly infrastructure issues are preventing me from continuing to use HTTP mode, so I'll also have to followup on #231 testing for you.

**Comment by brentleyjones** [comment]
[gRPC-instance1.txt](https://github.com/buchgr/bazel-remote/files/4370557/gRPC-instance1.txt)
[gRPC-instance2.txt](https://github.com/buchgr/bazel-remote/files/4370558/gRPC-instance2.txt)
[HTTP-instance1.txt](https://github.com/buchgr/bazel-remote/files/4370559/HTTP-instance1.txt)
[HTTP-instance2.txt](https://github.com/buchgr/bazel-remote/files/4370560/HTTP-instance2.txt)

I inserted a newline between the two builds. As you can see in instance 2 for gRPC, it can't find `ed11bb857931deee5257fae1ec0aeb51fc2e8be493c4af44315108c485613543`, but in instance 2 for HTTP it can.

**Comment by mostynb** [comment]
Are the logs above from a test branch with both this change and the commit from #231? If so, then the logic for disabling the gRPC AC dependency check must be broken- I can't see any `GRPC NODEPS AC GET ... OK` log lines.

**Comment by brentleyjones** [comment]
Yes, it has both commits from this and #231. This PR worked perfectly and can be merged, IMO. (I thought I was commenting in #231.)

**Pull request merged**
