### PR TITLE
Support LDAP authentication with unauthorized reads

### LINKED ISSUE #100: Support LDAP authentication
This is desirable for enterprise use.

### PR DESCRIPTION
**Pull request by JonasScharpf**
This PR is based on #101 and resolves #100

It provides unauthorized reads when using LDAP, config via command line args and minimal config file testing for the new LDAP section

This is my first GO thing ever, so it might not be perfect

### CODE REVIEW

**Review by mostynb — COMMENTED** [review]
Not bad, for first-time go code :) I will look some more tomorrow.

I wonder if there's a small ldap server we could spin up during an end-to-end test? https://github.com/bradleypeabody/godap might work.

**Comment by mostynb** [comment]
> so I've fixed your remarks and added a end-to-end fake LDAP server test. But the remaining `golangci` linter errors are beyond my knowledge to fix them by myself. I have to admit that I simply copied the httpServer thing from an example ...

Sorry it took me longer than expected to get back to this. I should have some time to read through this while I'm travelling later this week.

**Comment by JonasScharpf** [comment]
Hey @mostynb how are you doing? Might it be possible to find some time for this PR during your next trip? :wink:

**Comment by JonasScharpf** [comment]
@mostynb I'm sorry to ask again for your time + help with this PR, it's been now in review since almost 2 months

**Comment by mostynb** [comment]
Sorry this took me so long. I landed a modified version of this in #768. Could you please try it out?

Some of the bigger changes:
* I replaced ldap_tests.go with a shell script that uses https://github.com/glauth/glauth (.bazelci/ldap-tests.sh - it unfortunately only runs on linux at the moment)
* I had to add the BaseDN when calling `Bind`
* I changed the ldap.groups (slice) setting to a ldap.groups_query string

**Pull request closed without merging**
