### PR TITLE
added basic auth

### PR DESCRIPTION
**Pull request by bajacondor**
This allows for a basic auth check so that other people can't nefariously get to your cache.

### CODE REVIEW

**Comment by buchgr** [comment]
Awesome! Please ping me once it's ready for review.

**Comment by bajacondor** [comment]
Hello @buchgr, Thanks for this cool tool.  I'm somewhat new to Bazel, but this auth addition will help my team (I work for Nordstom Technology) get more out of Bazel in our shared pipelines and eventually will allow multiple teams to take advantage of the speed of cached builds without stepping on other teams' toes.
Unfortunately, I've hit a snag.   I was hoping to invoke the cache with a call like `build --remote_http_cache=http://user:password@bazel-remote-cache.local:8080` But it appears the Authorization header is stripped out by Bazel.  Do you know of any other method to pass the Authentication?
Thanks again.

**Comment by buchgr** [comment]
@bajacondor on it https://github.com/bazelbuild/bazel/pull/4609 :-)

**Comment by bajacondor** [comment]
Wow!  Thank you!  The next step is to add TLS listening to this remote cache server.  If you'd like, I can open another merge request for that and help you out.

**Comment by buchgr** [comment]
@bajacondor that would be awesome! I am currently quite busy with other stuff ... keep your PRs coming 🚀 🚀

**Pull request merged**
